"""
agents/interviewer.py
---------------------
Agent 1: The Interviewer — LangGraph node wrapper around LiveInterviewer.

Rules obeyed:
- Flash Live ONLY — never Pro (rules.md §1)
- Strictly separated from coach.py — no coaching logic here (rules.md §4)
- Standalone async function node — not a class method (rules.md §4)
- State is the only contract — no direct agent-to-agent calls (rules.md §4)
- Entity grounding enforced via system_instruction in streaming_manager (rules.md §3)
- Phase-aware: warm_up allows generic questions, deep_dive/stress_test must be entity-grounded
- Async throughout (rules.md §7)
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from core.state import InterviewState

if TYPE_CHECKING:
    from core.streaming_manager import LiveInterviewer

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Phase transition thresholds — SIMPLIFIED to 7-8 questions max
# ---------------------------------------------------------------------------

PHASE_THRESHOLDS: dict[str, int] = {
    "warm_up": 2,
    "deep_dive": 8,
    "stress_test": 12,
}


# ---------------------------------------------------------------------------
# Phase router — pure function, no I/O
# ---------------------------------------------------------------------------

def resolve_next_phase(current_status: str, turn_count: int) -> str:
    """
    Determines the next interview phase based on turn count.
    warm_up (2 turns) → deep_dive (6 turns) → stress_test (4 turns) → finished. Total: 12 turns max.

    Returns the same phase if threshold not yet reached.
    """
    match current_status:
        case "warm_up" if turn_count >= PHASE_THRESHOLDS["warm_up"]:
            return "deep_dive"
        case "deep_dive" if turn_count >= PHASE_THRESHOLDS["deep_dive"]:
            return "stress_test"
        case "stress_test" if turn_count >= PHASE_THRESHOLDS["stress_test"]:
            return "finished"
        case _:
            return current_status


# ---------------------------------------------------------------------------
# LangGraph node — interviewer_node
# ---------------------------------------------------------------------------

async def interviewer_node(
    state: InterviewState,
    live_interviewer: "LiveInterviewer",
) -> dict:
    """
    LangGraph node for Agent 1.

    Responsibilities:
    1. Check if a phase transition is needed and update LiveInterviewer accordingly.
    2. Sync the latest transcript from LiveInterviewer into state.
    3. Return partial state update (only changed keys).

    NOTE: This node does NOT drive the audio loop directly.
    The audio loop runs in api/websocket.py (send_audio / stream_response).
    This node is called by the orchestrator to sync state and manage phase transitions.
    """
    current_status: str = state.get("status", "warm_up")
    turn_count: int = state.get("turn_count", 0)

    # Resolve phase transition
    next_phase = resolve_next_phase(current_status, turn_count)

    # If phase changed, update the Live session's system_instruction
    if next_phase != current_status:
        logger.info(
            "Phase transition | session=%s | %s -> %s | turn=%d",
            state.get("session_id", "unknown"),
            current_status,
            next_phase,
            turn_count,
        )
        await live_interviewer.update_phase(next_phase)

    # Sync transcript from LiveInterviewer into state
    latest_transcript = live_interviewer.export_transcript()

    return {
        "status": next_phase,
        "turn_count": live_interviewer.turn_count,
        "transcript": latest_transcript,  # Annotated reducer appends, not replaces
    }


# ---------------------------------------------------------------------------
# Utility: build the opening greeting context
# ---------------------------------------------------------------------------

def get_opening_context(resume_json: dict) -> str:
    """
    Returns a brief context string the orchestrator can use to prime the
    first Flash Live message (warm_up phase opener).

    The actual greeting is generated by Flash Live from the system_instruction.
    This is just a human-readable summary for logging/debugging.
    """
    name_hint = resume_json.get("roles", [{}])[0].get("title", "the student") if resume_json.get("roles") else "the student"
    goals = resume_json.get("career_goals", "not specified")
    projects = [p.get("name") for p in resume_json.get("projects", [])]

    return (
        f"Interviewing: {name_hint} | "
        f"Goals: {goals} | "
        f"Projects to anchor: {projects}"
    )
